### ISSUE TITLE
Calculation of d'

### ISSUE THREAD

**Issue by mattminder** [joaquinanguera/aceR#32]
Hello,

I think I've found some bugs in the calculation of the d' value in the file `aceR/R/math-detection.R`. 

In the paper "Calculation of signal detection theory measures" (Stanislaw 1999), hit rate H and false alarm rate F are defined as: 
- Hit rate: The probability of responding yes on signal trials, i.e. `hr = num_hits / num_targets`
- False-alarm rate: The probability of responding yes on noise trials, i.e. `far = num_false_alarm / num_nontargets`.
And finally the d' is defined as `qnorm(hr) - qnorm(far)`.

Meanwhile, lines 36 and 37 of `aceR/R/math-detection.R` define the false alarm rate and hit rate differently:
`out$false_alarm_rate = freq$false_alarm / num_nontargets`
`out$hit_rate = freq$hit / num_nontargets`
This different definition of the hit rate (division by the number of nontargets instead of the number of targets) will yield a different d' value. 

Furthermore, the function `ace_dprime` uses yet another definition of the false alarm rate and hit rate, there the hit rate is defined as the number of hits divided by the total number of trials, and similarly the false alarm rate is the number of false alarms divided by the total number of trials, which will give yet another d'. 

Is this a bug or is there something I'm not seeing?

Thanks :)

**Comment by monicathieu** [comment]
Hi Matt,

Thanks for looking through this! It looks like there are indeed some bugs(!), as well as some places I can document better and eventually delete very old, deprecated code.

1. [`ace_detection()`](https://github.com/joaquinanguera/aceR/blob/835f91acc5e5edd7ddb611b4ac29c38c4b05523d/R/math-detection.R#L4) is  long deprecated (some of these are remnants from a verrrry old, like circa 2015, version of this package). I haven't deleted this function and its calling function, `ace_detection_rate()`, purely out of fear that something will break, but this code truly has no use anymore so it's best deleted to clean up the package.
2. `ace_dprime()` and `ace_dprime_wide()` in that same file _are_ used--the former for SAAT and TNT data, and the latter for Filter. I think you're right that `ace_dprime()` is currently lumping target and non-target trials together in the denominator of hit and FA rates, by counting the entire length of the column instead of only the length of the target and non-target portions. And because `qnorm()` is a nonlinear transformation, the resulting d' will be off, and in general be lower than it should be. (I think rank-order relationships between participants should be preserved, but the d' is off!!)

This is pretty serious but also easy to fix so I will patch this ASAP. Thank you for catching this! The more eyeballs the better.

**Comment by mattminder** [comment]
Perfect, thanks for the quick response!
