### ISSUE TITLE
Columns in ACE output file renamed leading to error in processing

### ISSUE THREAD

**Issue by joshvolponi** [joaquinanguera/aceR#49]
Problem: Column N and P of the ACE demographics file were renamed, which seems to be causing an error in processing

Error provided in the R script: _Error in if (mask$get_size() > 0) { : argument is of length zero_

Potential solution: Update aceR script to handle "Participant ID" for column N and "PID" for column Y of the demographics file. In previous versions they were set as "Nexus.Id" and "Participant.Id" respectively

**Comment by monicathieu** [comment]
Hi! Clarifying questions:

1. Is the R script that is erroring erroring directly out of an aceR function, or is the aceR function returning something but a downstream line of the user's script is then erroring because the aceR output was unexpected?
2. The `development` branch of this repo is implementing changes related to the ACE Nexus big version update. There are a couple sticky cases I haven't been able to finish yet, but it mostly works. Are these ACE demo file column renames coming straight out of Nexus? If so, I would recommend having the user install the `development` branch. (Bonus that if they catch bugs there, they're helping get Nexus development closer to completion!)

**Comment by monicathieu** [comment]
Confirming that whatever change closes #51 will also close this. aceR on the development branch for Nexus should already coerce "Participant ID" and "participant.Id" or "participantID" etc. all to "participant_id" under the hood. However, "PID" will not get caught unless this is a newly expected column. that we should keep, separately from the participant ID column. I will keep discussion of the new participant ID column name handling over on #51 and we'll close both at the same time when I get enough info to update the code.
